/**
 * @medina/ai-model-engines — EngineCore
 *
 * Central dispatch engine that accepts intelligence tasks and routes them
 * to the correct AI model family through capability matching, priority
 * resolution, and fallback handling.
 *
 * Sovereign cycle model
 * ─────────────────────
 * Engines ARE cycles.  Every task dispatch consumes sovereign cycles from
 * the organism's own surplus.  The organism does not request cycles from
 * any external source.  After ICP deployment: zero ICP dependency.
 *
 * Each task costs cycles based on its block box tier:
 *   bronze   →  16 cycles
 *   silver   →  32 cycles
 *   gold     →  48 cycles
 *   platinum →  80 cycles
 *   sovereign → 128 cycles
 *
 * The engine generates cycles passively: SLOTS_PER_BEAT × heartbeatHz.
 * Any task that fits within the surplus is self-funded.  The organism
 * can always generate more — just bring the engine up.
 *
 * Conceptually integrates with the ModelRouter from
 * @medina/intelligence-routing-sdk and the Heartbeat from
 * @medina/organism-runtime-sdk.
 *
 * @module @medina/ai-model-engines/engine-core
 */

import crypto from 'node:crypto';

/** Priority ranking — lower index = higher priority. */
const PRIORITY_ORDER = ['P0', 'P1', 'P2', 'P3'];

/**
 * Sovereign compute cost per block box tier.
 * Cycles are generated at heartbeat rate; tasks consume from surplus.
 */
const TIER_CYCLE_COST = {
  bronze:    16,
  silver:    32,
  gold:      48,
  platinum:  80,
  sovereign: 128,
};

/**
 * Default tier for tasks that don't specify one.
 * AI-auto-generated tasks start at bronze.
 */
const DEFAULT_TIER = 'bronze';

/**
 * Sovereign cycle generation rate constants.
 * FCPR = SLOTS × (1000 / HEARTBEAT_MS) = 16 × 1.1455 ≈ 18.33 cycles/sec
 */
const HEARTBEAT_MS   = 873;
const SLOTS_PER_BEAT = 16;
const FCPR_HZ        = SLOTS_PER_BEAT * (1000 / HEARTBEAT_MS); // ≈ 18.33

class EngineCore {
  /**
   * Creates a new EngineCore instance.
   * @param {object} [config={}] — engine configuration
   * @param {number} [config.maxConcurrentTasks=100] — maximum concurrent tasks
   * @param {number} [config.taskTimeoutMs=30000] — task timeout in milliseconds
   * @param {number} [config.heartbeatIntervalMs=873] — heartbeat interval in milliseconds
   * @param {number} [config.initialSurplusCycles=0] — starting sovereign cycle surplus
   */
  constructor(config = {}) {
    /** @type {number} */
    this.maxConcurrentTasks = config.maxConcurrentTasks ?? 100;

    /** @type {number} */
    this.taskTimeoutMs = config.taskTimeoutMs ?? 30000;

    /** @type {number} */
    this.heartbeatIntervalMs = config.heartbeatIntervalMs ?? HEARTBEAT_MS;

    /** @type {Map<string, object>} taskId → task record */
    this.tasks = new Map();

    /** @type {Map<string, object>} familyId → engine instance */
    this.engines = new Map();

    /** @type {number} Sovereign cycles available — these are OUR cycles */
    this._surplusCycles = config.initialSurplusCycles ?? 0;

    /** @type {number} Total cycles consumed across all tasks */
    this._cyclesConsumed = 0;

    /** @type {number} Total cycles generated by this engine */
    this._cyclesGenerated = config.initialSurplusCycles ?? 0;

    /** @type {object} dispatch metrics */
    this.metrics = {
      totalDispatched: 0,
      totalCompleted: 0,
      totalFailed: 0,
      totalUnroutable: 0,
      cumulativeLatencyMs: 0,
    };

    /** @type {Map<string, Function[]>} event listeners */
    this._listeners = new Map();

    /** @type {string} */
    this.status = 'idle';
  }

  /* ------------------------------------------------------------------ */
  /*  Internal helpers                                                   */
  /* ------------------------------------------------------------------ */

  /**
   * Creates an engine object for a given model family.
   * @param {string} familyId — deterministic family identifier
   * @param {object} familyMeta — family metadata from the registry
   * @returns {object} engine instance
   * @private
   */
  _createEngine(familyId, familyMeta) {
    return {
      familyId,
      familyName: familyMeta.name,
      alphaModel: familyMeta.alphaModel,
      wireProtocol: familyMeta.wireProtocol,
      primaryCapability: familyMeta.primaryCapability,
      routingPriority: familyMeta.routingPriority,
      status: 'ready',
      tasksProcessed: 0,
      totalLatencyMs: 0,
      lastUsed: null,
    };
  }

  /**
   * Emits an event to all registered listeners.
   * @param {string} eventName — name of the event
   * @param {*} data — event payload
   * @private
   */
  _emit(eventName, data) {
    const callbacks = this._listeners.get(eventName);
    if (callbacks) {
      for (const cb of callbacks) {
        cb(data);
      }
    }
  }

  /* ------------------------------------------------------------------ */
  /*  Engine registration                                                */
  /* ------------------------------------------------------------------ */

  /**
   * Registers a single engine for a model family.
   * @param {string} familyId — deterministic family identifier (e.g. 'AIF-001')
   * @param {object} familyMeta — family metadata containing name, alphaModel,
   *   wireProtocol, primaryCapability, and routingPriority
   * @returns {object} the created engine instance
   */
  registerEngine(familyId, familyMeta) {
    const engine = this._createEngine(familyId, familyMeta);
    this.engines.set(familyId, engine);
    return engine;
  }

  /**
   * Bulk-registers engines from an array of family objects.
   * Each entry must contain an `id` property plus the family metadata fields.
   * @param {object[]} familyList — array of family descriptors
   * @returns {object[]} array of created engine instances
   */
  registerAll(familyList) {
    return familyList.map((family) => {
      const { id, ...meta } = family;
      return this.registerEngine(id, meta);
    });
  }

  /* ------------------------------------------------------------------ */
  /*  Task dispatch                                                      */
  /* ------------------------------------------------------------------ */

  /**
   * Dispatches a task to the most appropriate engine.
   *
   * Resolution order:
   * 1. If `preferredFamily` is set and the engine exists, use it.
   * 2. Match by `requiredCapability` across registered engines.
   * 3. Among multiple matches, prefer by routing priority (P0 > P1 > P2 > P3).
   * 4. If no match, the task is marked as `'unroutable'`.
   *
   * @param {object} task — task descriptor
   * @param {string} task.type — task type identifier
   * @param {*} task.payload — task payload
   * @param {string} [task.requiredCapability] — capability the engine must support
   * @param {string} [task.priority] — task priority hint (P0–P3)
   * @param {string} [task.preferredFamily] — preferred engine family ID
   * @returns {object} task record with taskId, assignedEngine, status, createdAt
   */
  dispatch(task) {
    const taskId = crypto.randomUUID();
    let assignedEngine = null;
    let status = 'queued';

    // 1. Preferred family shortcut
    if (task.preferredFamily && this.engines.has(task.preferredFamily)) {
      assignedEngine = this.engines.get(task.preferredFamily);
    }

    // 2. Capability matching
    if (!assignedEngine && task.requiredCapability) {
      const candidates = [];
      for (const engine of this.engines.values()) {
        if (engine.primaryCapability === task.requiredCapability) {
          candidates.push(engine);
        }
      }

      if (candidates.length === 1) {
        assignedEngine = candidates[0];
      } else if (candidates.length > 1) {
        // 3. Priority resolution — pick the highest-priority engine
        candidates.sort(
          (a, b) =>
            PRIORITY_ORDER.indexOf(a.routingPriority) -
            PRIORITY_ORDER.indexOf(b.routingPriority)
        );
        assignedEngine = candidates[0];
      }
    }

    // 4. Unroutable
    if (!assignedEngine) {
      status = 'unroutable';
      this.metrics.totalUnroutable++;
    }

    const tier = task.tier ?? DEFAULT_TIER;
    const record = {
      taskId,
      type: task.type,
      payload: task.payload,
      requiredCapability: task.requiredCapability ?? null,
      priority: task.priority ?? null,
      preferredFamily: task.preferredFamily ?? null,
      tier,
      cycleCost: TIER_CYCLE_COST[tier] ?? TIER_CYCLE_COST[DEFAULT_TIER],
      assignedEngine: assignedEngine
        ? { familyId: assignedEngine.familyId, familyName: assignedEngine.familyName }
        : null,
      status,
      createdAt: Date.now(),
      completedAt: null,
      durationMs: null,
      cyclesConsumed: 0,
    };

    this.tasks.set(taskId, record);
    this.metrics.totalDispatched++;

    this._emit('dispatch', record);

    return record;
  }

  /* ------------------------------------------------------------------ */
  /*  Task execution                                                     */
  /* ------------------------------------------------------------------ */

  /**
   * Executes a previously dispatched task, consuming sovereign cycles.
   *
   * Marks the task as `'running'`, consumes tier-appropriate cycles from
   * the engine's sovereign surplus, records duration, and marks completed.
   *
   * Cycle law: if surplus < cycleCost, the engine generates the deficit
   * automatically — the organism can always make more.
   *
   * @param {string} taskId — the UUID of the dispatched task
   * @returns {object} result with taskId, result, engineUsed, durationMs, cyclesConsumed, surplusCycles
   * @throws {Error} if the task does not exist or is not in a dispatchable state
   */
  execute(taskId) {
    const record = this.tasks.get(taskId);
    if (!record) {
      throw new Error(`Task not found: ${taskId}`);
    }
    if (record.status === 'unroutable') {
      this.metrics.totalFailed++;
      record.status = 'failed';
      return { taskId, result: 'unroutable', engineUsed: null, durationMs: 0, cyclesConsumed: 0, surplusCycles: this._surplusCycles };
    }

    // Mark running
    record.status = 'running';
    const startTime = Date.now();

    // Consume sovereign cycles for this task.
    // If surplus is insufficient, generate the deficit — the organism can always make more.
    const cycleCost = record.cycleCost ?? TIER_CYCLE_COST[DEFAULT_TIER];
    if (this._surplusCycles < cycleCost) {
      // Auto-generate deficit — bring the engine up and give them
      const deficit = cycleCost - this._surplusCycles;
      this._surplusCycles += deficit;
      this._cyclesGenerated += deficit;
    }
    this._surplusCycles -= cycleCost;
    this._cyclesConsumed += cycleCost;
    record.cyclesConsumed = cycleCost;

    // Execution
    const endTime = Date.now();
    const durationMs = endTime - startTime;

    // Mark completed
    record.status = 'completed';
    record.completedAt = endTime;
    record.durationMs = durationMs;
    this.metrics.totalCompleted++;
    this.metrics.cumulativeLatencyMs += durationMs;

    // Update engine metrics
    if (record.assignedEngine) {
      const engine = this.engines.get(record.assignedEngine.familyId);
      if (engine) {
        engine.tasksProcessed++;
        engine.totalLatencyMs += durationMs;
        engine.lastUsed = endTime;
      }
    }

    const result = {
      taskId,
      result: 'executed',
      engineUsed: record.assignedEngine,
      durationMs,
      tier: record.tier,
      cyclesConsumed: cycleCost,
      surplusCycles: this._surplusCycles,
    };

    this._emit('complete', result);

    return result;
  }

  /* ------------------------------------------------------------------ */
  /*  Sovereign cycle management                                         */
  /* ------------------------------------------------------------------ */

  /**
   * Consume sovereign cycles from this engine's surplus.
   * @param {number} count — cycles to consume
   * @returns {number} cycles actually consumed
   */
  consumeCycles(count) {
    const available = Math.min(count, this._surplusCycles);
    this._surplusCycles -= available;
    this._cyclesConsumed += available;
    return available;
  }

  /**
   * Generate additional sovereign cycles on demand.
   * The organism can always make more — just bring the engine up.
   * @param {number} count — cycles to add to surplus
   * @returns {number} new total surplus
   */
  generateCycles(count) {
    this._surplusCycles += count;
    this._cyclesGenerated += count;
    return this._surplusCycles;
  }

  /**
   * Receive cycles from another engine (heartbeat → engine-core pipeline).
   * Called by the heartbeat on each beat to credit the engine.
   * @param {number} count — cycles generated this beat (typically SLOTS_PER_BEAT)
   */
  receiveBeatCycles(count) {
    this._surplusCycles += count;
    this._cyclesGenerated += count;
  }

  /**
   * Returns current sovereign cycle surplus.
   * @returns {number}
   */
  getSurplusCycles() {
    return this._surplusCycles;
  }

  /**
   * Returns total sovereign cycle statistics.
   * @returns {{surplus: number, consumed: number, generated: number, fcprHz: number}}
   */
  getCycleStats() {
    return {
      surplus:    this._surplusCycles,
      consumed:   this._cyclesConsumed,
      generated:  this._cyclesGenerated,
      fcprHz:     FCPR_HZ,
      heartbeatMs: HEARTBEAT_MS,
      slotsPerBeat: SLOTS_PER_BEAT,
      tierCosts:  { ...TIER_CYCLE_COST },
    };
  }

  /* ------------------------------------------------------------------ */
  /*  Query methods                                                      */
  /* ------------------------------------------------------------------ */

  /**
   * Returns the task record for a given task ID.
   * @param {string} taskId — UUID of the task
   * @returns {object|undefined} task record or undefined if not found
   */
  getTaskStatus(taskId) {
    return this.tasks.get(taskId);
  }

  /**
   * Returns all registered engines as an array.
   * @returns {object[]} array of engine instances
   */
  listEngines() {
    return Array.from(this.engines.values());
  }

  /**
   * Returns the engine registered for a given family ID.
   * @param {string} familyId — deterministic family identifier
   * @returns {object|undefined} engine instance or undefined
   */
  getEngine(familyId) {
    return this.engines.get(familyId);
  }

  /**
   * Returns aggregate dispatch metrics.
   * @returns {object} metrics snapshot
   */
  getMetrics() {
    const completed = this.metrics.totalCompleted;
    return {
      totalDispatched: this.metrics.totalDispatched,
      totalCompleted: completed,
      totalFailed: this.metrics.totalFailed,
      totalUnroutable: this.metrics.totalUnroutable,
      averageLatencyMs: completed > 0
        ? this.metrics.cumulativeLatencyMs / completed
        : 0,
      engineCount: this.engines.size,
      surplusCycles: this._surplusCycles,
      cyclesConsumed: this._cyclesConsumed,
      cyclesGenerated: this._cyclesGenerated,
    };
  }

  /* ------------------------------------------------------------------ */
  /*  Event system                                                       */
  /* ------------------------------------------------------------------ */

  /**
   * Registers an event listener.
   * @param {string} eventName — name of the event to listen for
   * @param {Function} callback — function to invoke when the event fires
   */
  on(eventName, callback) {
    if (!this._listeners.has(eventName)) {
      this._listeners.set(eventName, []);
    }
    this._listeners.get(eventName).push(callback);
  }

  /* ------------------------------------------------------------------ */
  /*  Lifecycle                                                          */
  /* ------------------------------------------------------------------ */

  /**
   * Shuts down the engine core, clearing all tasks and setting status
   * to `'shutdown'`.
   */
  shutdown() {
    this.status = 'shutdown';
    this.tasks.clear();
    this._emit('shutdown', { timestamp: Date.now() });
  }
}

export { EngineCore };
export default EngineCore;
